version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    expose:
      - "6000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 6000

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./app/static:/app/static
      - ./app/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app